### ISSUE TITLE
Migrate to Python3 instead of Bash?

### ISSUE THREAD

**Issue by pocc** [pocc/pre-commit-hooks#13]
@guihao-liang @sparfenyuk @TheButlah @zbeekman @bsergean You guys have interacted with this repo and I'd like your input. Issues have been created in part due to how bash parses strings or interacts with arrays/hash maps (#5, #9, #10),  or how it's not even the same across platforms (#4 - thanks to zbeekman for a likely fix).

Python is required [to install](https://pre-commit.com/#installation) pre-commit and so everyone using pre-commit already has it on their system. Python has more predictable behavior, which is what I'm aiming for here in contrast to bash (e.g. `${args[*]}` vs `${args[@]}`). It's also a well-known glue language for C/C++, so it would fit well here.

Thoughts?

**Comment by bsergean** [comment]
I think it would be a good choice. The only downside I can think about now is startup time, which will be slightly slower for python ; however much of the runtime cost will be due to clang-format, which makes this a moot point.

Windows support will come for free too. And even on some Linux systems bash isn't installed.

**Comment by guihao-liang** [comment]
I'm down for it! Just let me know if you have any plans for working on it. It's definitely cross-platform. The run-time to parse args should be negligible. 

Besides rewriting the code,  you may also have to pack the python code into a package and publish it to PyPI, which is a standard way to avoid that `readlink` problem for importing local libs.

**Comment by TheButlah** [comment]
I'm down for it. The only thing to consider is the potential complexity of dealing with selecting the proper python interpreter/virtualenv to use. I think it should be the same one that pre-commit is using, to ensure consistency

**Comment by guihao-liang** [comment]
from a similar pre-commit hook repo, its [shellcheck](https://github.com/jumanjihouse/pre-commit-hooks/blob/master/pre_commit_hooks/shellcheck) is just a thin wrapper for `shellcheck`, which is similar to this project. 

```
readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

shellcheck "$@"
```

Why not just simply call `clang-format` directly using shell? It's simple.

**Comment by pocc** [comment]
It would be this simple if each of these utilities were shellcheck. There are two problems with this approach.

1) Pre-commit [does not handle](https://github.com/pre-commit/pre-commit/issues/1000) arguments after `--` correctly. This is a bug and the author says he wont fix this
2) Oclint does not exit with an error status code on error, so output needs to be checked

**Comment by guihao-liang** [comment]
> It would be this simple if each of these utilities were shellcheck. There are two problems with this approach.
> 
> 1. Pre-commit [does not handle](https://github.com/pre-commit/pre-commit/issues/1000) arguments after `--` correctly. This is a bug and the author says he wont fix this.
> 2. Some utilities do not exit with an error status code on error, or output warnings which trigger a pre-commit failure. For this reason, output needs to be checked and sanitized.

Glad to know this!

**Comment by guihao-liang** [comment]
any plan?

**Comment by pocc** [comment]
## ✨New✨ python version available (tag v1.0.0-beta)

@guihao-liang @sparfenyuk @TheButlah @bsergean Python version is now available (use rev: python). Please test it if you have time.

The API should be maintained, so this shouldn't be a breaking change. I plan on pushing this on April 1 barring problems with it. 

## On PyPI

It is also available via pip as [CLinters](https://pypi.org/project/CLinters/) if you want to get expected return codes for these utilities outside of pre-commit. Commands are registered as `$cmd`-hook like `clang-format-hook`.

**Comment by pocc** [comment]
It's been moved, and ~85 tests now run on Travis for this repo for 5 linters on ubuntu/macos.

**Comment by bsergean** [comment]
Thanks ! / I've been trying to use your new code but I couldn't find the rev (pre-commit was giving me an error). Also I've been looking for a way to add ignore folders, for the third_party code that I have in one folder. 

This is my repo fyi (https://github.com/machinezone/IXWebSocket)

**Comment by pocc** [comment]
Cool project! I took a look at your repo, but it doesn't look like you're using this repo currently.
Why not create a separate issue for this? 

Post the error and your pre-commit config and I'd be happy to take a look at it.

**Comment by bsergean** [comment]
Great. I'll try to do that asap, I'm tired of forgetting to run clang-format manually ... and I need to look into clang-tidy and friends.

**Comment by pocc** [comment]
In terms of exploration, there are formatters and static code analyzers. All of these are active projects.

clang-format and uncrustify are formatters and you should only use one so they don't argue. clang-format is part of clang and allows you to target a formatting style with `--style`. Whereas uncrustify doesn't seem as mature, but does have a lot of knobs.

clang-tidy, oclint, and cppcheck are static code analyzers. They test for different things (i.e. using more is better). They will find bugs and recommend solutions. As with any linter, if you add one, you may see an inordinate number of warnings/errors that it wants you to fix, which can be a pain.
