### ISSUE TITLE
"-p" checking for oclint/clang-tidy always fails

### ISSUE THREAD

**Issue by rambo** [pocc/pre-commit-hooks#15]
if "-p" is specified alone (so the "-p" in args -check could succeed) clang-tidy complains about missing value.

If it's specified correctly for clang-tidy ("-p=cmake-build-debug") then the check fails and the -D is added which makes clang-tidy not find for example included libraries...

I will submit a PR soonish.

**Comment by pocc** [comment]
Thanks for noticing this. I think I'm just going to delete the `add_if_missing` for `-- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON` because the stderr due to its lack is useful information. I saw your commit, which also fixes this issue.
