### ISSUE TITLE
clang-tidy defaults: -checks=* is problematic

### ISSUE THREAD

**Issue by rambo** [pocc/pre-commit-hooks#17]
There is a conflict:

modernize wants to use trailing return type https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-trailing-return-type.html

but Fuchsia disallows it https://clang.llvm.org/extra/clang-tidy/checks/fuchsia-trailing-return.html

maybe set the default to `"-checks=*,-fuchsia*"` ? If someone is specifically targeting Fuchsia they probably need to disable some other default checks than modernize as well...

**Comment by pocc** [comment]
Expected behavior for `add_if_missing(["-checks=*"])` is to add `-checks=*` if there are no `-checks[ =].*` arguments provided. If you add fuchsia checks, then `-checks=*` **shouldn't** be added.

The reason it's added is so that clang-tidy does something by default if no other arguments besides file are provided.

**Comment by rambo** [comment]
Yes, I figure that out and it does work. My issue is that the default leads to a situation where checks always fail because of this conflict (and documentation "suggests" using `checks=*` by listing it as an example).

It's just a documentation/smart defaults issue, nothing too bad (but it did confuse the hell out of me before I figured that I need to explicitly disable fuchsia checks)

**Comment by pocc** [comment]
What's your version of llvm?

**Comment by pocc** [comment]
And update the documentation to target the specific rule that's being broken.

**Comment by rambo** [comment]
```
➜  ~ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build.
  Default target: x86_64-apple-darwin19.4.0
  Host CPU: skylake
```

llvm installed from homebrew.

The specific conflict is between those two rules linked in the first post `-warnings-as-errors=*` was enabled as well

**Comment by pocc** [comment]
You're completely right here. I'm going to fix this in a coming commit and update documentation at the same time. 

Cheers for noticing -checks=* can conflict => that's going into documentation.
