### ISSUE TITLE
can `--version` enforce using a clang-format version if more than one are installed?

### ISSUE THREAD

**Issue by nikolakop** [pocc/pre-commit-hooks#27]
Thanks for the great hooks!

My interpretation of the documentation was that `--version=X` would try to enforce using version X of a linter. However, it seems that it only validates the correct version is used.
E.g. in one of my ubuntu machines, the `clang-format` binary is at version 10, but version 11 is also installed (as `clang-format-11`). 

Would it make sense that `--version=11` would try to use the latter? Otherwise, could we have a knob exposed for the binary that the hook will use?

**Comment by pocc** [comment]
Do you use both clang-format versions 10 and 11? It would be easy to make `clang-format` point to the clang-format-11 binary.

**Comment by nikolakop** [comment]
Sure, I know this can be done. I just didn't want to force everyone in my team to have the same setup as me. But at first I wanted to make sure that I had wrong expectations on the behavior here.

However, as you point out, having different repos that require different `clang-format` versions and needing to have both installed sounds like a valid use case.

**Comment by pocc** [comment]
Expected behavior here is for pre-commit-hooks to check the version of `clang-format` and fail if it's wrong.

>  I just didn't want to force everyone in my team to have the same setup as me. 

That's kind of point of enforcing a version: So that when you run the linter, you get the same output as your coworker. Specifying a specific binary by filepath is probably going to break across machines as it's not guaranteed that people have this utility installed in the same place.

**Comment by nikolakop** [comment]
Just to clarify, I meant I didn't want to enforce everyone to have the same _default_ clang-format version as me. It's not a big deal for me indeed. Thanks a lot for your time and clarifications.

But I think this discussion did raise the point of what does a dev do if working at the same machine on two different projects (and repos) that use the pre-commit hooks for cpp, and for whatever reason one relies on clang format 11 and the other on 13? (note that the format styles are not compatible with each other between major versions). I guess in that case one could add an extra git hook in each repo that would symlink the default clang-format to the appropriate binary. This is not really my case, but just wondering.

Thanks again for the great tool.

**Comment by henryiii** [comment]
FYI, might be worth looking https://github.com/ssciwr/clang-format-wheel; you can now install an exact version of clang-format (10, 11, or 12) from PyPI for all common platforms, 1-2 MB wheel. There's also a pre-commit hook for it pinned to the released versions, `autoupdate`able.: https://github.com/ssciwr/clang-format-precommit . This enforces the exact same version of clang-format for all usages (including pre-commit.ci, of course).

**Comment by pocc** [comment]
I appreciate the input here.

I think it's important to have a separation of concerns here. These pre-commit hooks call utilities, but installation thereof is a separate concern and should be documented in the README.md. Your repo has versions tied to rev, which is clever, but won't work when one repo has one rev but 7 hooks.

If you would like to PR the README.md with a pip command to install specific clang-format versions in the [installation section](https://github.com/pocc/pre-commit-hooks#installation), I'd be happy to merge.

**Comment by henryiii** [comment]
I made the same point [here](https://github.com/ssciwr/clang-format-wheel/issues/8#issuecomment-929302265), actually. :)
