### ISSUE TITLE
Less strict version check

### ISSUE THREAD

**Issue by jeremy-coulon** [pocc/pre-commit-hooks#3]
Hello,
Thank you for these hooks. They're great.
I am using clang-format hook.

I'd like to check version of clang-format tool but I think it is too strict.
I'd like to put in my config '--version=6.0'. But some people in my team are using version '6.0.1' while others are using version '6.0.0-1ubuntu2'.

I would be nice to be able to specify a version pattern instead of a strict version. Or use Semantic Versioning if it makes sense.

**Comment by pocc** [comment]
Cheers and good idea. This should be fixed now. '6.0' matches '6.0.1' and '6.0.0-1ubuntu2', but not '6.1.'
Let me know if this solution doesn't work for you.
