### ISSUE TITLE
Resolve Tooling and support multiple version of clang-tidy

### ISSUE THREAD

**Issue by sanrut01** [pocc/pre-commit-hooks#41]
Currently, the hooks require tooling to be available on the machines where the hooks are running.  Would the project be open to supporting specifying which version of clang-tidy to download and download the appropriate version on the machine as part of pre-commit so that the user doesn't have to worry about installing the tooling?

The upstream has [clang-tidy releases](https://github.com/muttleyxd/clang-tools-static-binaries/releases) multiple versions of clang-tidy.
and the pre-commit for clang downloads the specific version corresponding to os based on version arg provided for the hook.

Happy to look into a patch along these lines.

**Comment by pocc** [comment]
That's great. So if it's part of some github workflow etc., they can download it from https://github.com/muttleyxd/clang-tools-static-binaries/releases and get the one they need.

pre-commit hooks are a wrapper over inserting a couple lines of git commands and linters into your `./git/source/pre-commit` file.
