### ISSUE TITLE
clang format failed

### ISSUE THREAD

**Issue by ypearson** [pocc/pre-commit-hooks#54]
```
pre-commit run
clang-format.............................................................Failed
- hook id: clang-format
- exit code: 1

firmware/src/main.cpp
====================
--- original
+++ formatted
@@ -33,7 +33,7 @@
 // Section: Main Entry Point
 // *****************************************************************************
 // *****************************************************************************
-int x= 0;
+int x = 0;
 int main(void) {

```
```
which clang-format
/home/USER/.local/bin/clang-format
```

Ubuntu 22 LTS
clang-format LLVM installed locally

Any way to find out why it failed?

thanks

**Comment by gsmithufl** [comment]
It literally tells you right there. It says your file is incorrectly formatted and provides the diff of the change.

**Comment by pocc** [comment]
I'm agreeing with Garrett here. You can see that in`x= 0`, there's no space between x and =:

```
-int x= 0;
+int x = 0;
```

You may want to read up on how to read diffs: https://unix.stackexchange.com/questions/81998/understanding-of-diff-output

Closing this.
